import mongoose from "mongoose";

/**
 * Review Schema
 * 
 * Represents PR reviews generated by the AI agent.
 * Stores review content, metadata, and GitHub integration details.
 * Indexed for efficient queries by user and date.
 */

const reviewSchema = new mongoose.Schema(
  {
    id: {
      type: String,
      required: true,
      unique: true,
      index: true,
      description: "Application-generated ID (e.g., review_xxxxx)",
    },
    userId: {
      type: String,
      required: true,
      index: true,
      description: "ID of user who created this review",
    },
    input: {
      issueUrl: String,
      issueText: String,
      prUrl: String,
      prText: String,
      previousCode: String,
      currentCode: String,
      companyName: String,
      companyGuidelines: String,
    },
    review: {
      type: String,
      required: true,
      description: "AI-generated review content",
    },
    meta: {
      rating: String,
      summary: String,
      label: String,
    },
    githubPr: {
      title: String,
      author: String,
      changedFiles: Number,
      additions: Number,
      deletions: Number,
      headBranch: String,
      baseBranch: String,
      htmlUrl: String,
    },
    githubCommentUrl: {
      type: String,
      default: "",
      description: "URL of comment posted to GitHub (if enabled)",
    },
    createdAt: {
      type: Date,
      default: Date.now,
      immutable: true,
      index: true,
    },
  },
  {
    collection: "reviews",
    strict: true,
  }
);

// Composite index for efficient user review queries sorted by date
reviewSchema.index({ userId: 1, createdAt: -1 });

const Review = mongoose.model("Review", reviewSchema);

export default Review;
